# Site settings
title: bol0bal4
email: vunhan93@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Linux, FOSS, DIY, INTP...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://vunhan.github.io/" # the base hostname & protocol for your site
twitter_username: VuNhanUit
github_username:  vunhan

# Build settings
markdown: kramdown
